apiVersion: apisix.apache.org/v1alpha1
kind: GatewayProxy
metadata:
  name: default
  namespace: apisix
spec:
  provider:
    type: ControlPlane
    controlPlane:
      endpoints:
        - http://apisix-admin.apisix.svc.cluster.local:9180
      auth:
        type: AdminKey
        adminKey:
          value: "edd1c9f034335f136f87ad84b625c8f1"
