apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cleanup-images-
  namespace: tekton-ci
spec:
  taskRunTemplate:
    serviceAccountName: cleanup-images-sa
  pipelineRef:
    resolver: git
    params:
      - name: repo
        value: tekton-pac-pipelines
      - name: pathInRepo
        value: pipelines/cleanup-images.yaml
