apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cleanup-images-
  namespace: ci
spec:
  pipelineRef:
    resolver: git
    params:
      - name: repo
        value: tekton-pac-pipelines
      - name: pathInRepo
        value: pipelines/cleanup-images.yaml
  taskRunTemplate:
    serviceAccountName: tekton-pipeline-sa
