apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: "{{ repo_name }}-install-ca-"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: >
      event == "push" && target_branch == "main" &&
      ("files/***".pathChanged() || "install-ca.yml".pathChanged() ||
       ".tekton/install-ca.yaml".pathChanged())
spec:
  taskRunTemplate:
    serviceAccountName: ansible-run-sa
  pipelineRef:
    resolver: git
    params:
      - name: repo
        value: tekton-pac-pipelines
      - name: pathInRepo
        value: pipelines/run-ansible-playbook.yaml
  params:
    - name: gitea-org
      value: "{{ repo_owner }}"
    - name: repo-name
      value: "{{ repo_name }}"
    - name: revision
      value: "{{ revision }}"
    - name: playbook
      value: install-ca.yml
    - name: inventory
      value: inventory/minikube.ini #minikube test target; switch to inventory/hosts.ini for prod.
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          storageClassName: standard #TBR
          resources:
            requests:
              storage: 1Gi
    - name: ssh-key
      secret:
        secretName: ansible-node-ssh
