gitea:
  admin:
    username: admin
    password: "admin"
    email: "admin@gitea.local"
  config:
    server:
      ROOT_URL: http://gitea.127.0.0.1.nip.io:8080
    webhook:
      ALLOWED_HOST_LIST: "*"

# Sin persistencia para entorno de desarrollo efímero
persistence:
  enabled: false

postgresql-ha:
  enabled: false

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: false

service:
  http:
    type: ClusterIP
    port: 3000
