apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-images
spec:
  description: >
    Cleans up Harbor images, keeping undeployed builds newer than the deployed
    version, the deployed version itself, and the previous one as rollback
    target. Deletes everything older.
  steps:
    - name: cleanup
      image: harbor.harbor.svc.cluster.local:80/cnie-c0-infra/ci-utils:latest #TBR
      args: ["/app/scripts/cleanup_images.py"]
      computeResources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 512Mi
      env:
        - name: ARGOCD_URL
          valueFrom:
            secretKeyRef:
              name: argocd-creds
              key: url
        - name: ARGOCD_USER
          valueFrom:
            secretKeyRef:
              name: argocd-creds
              key: username
        - name: ARGOCD_PASS
          valueFrom:
            secretKeyRef:
              name: argocd-creds
              key: password
        - name: HARBOR_URL
          valueFrom:
            secretKeyRef:
              name: harbor-creds
              key: url
        - name: HARBOR_USER
          valueFrom:
            secretKeyRef:
              name: harbor-creds
              key: username
        - name: HARBOR_PASS
          valueFrom:
            secretKeyRef:
              name: harbor-creds
              key: password
