# Credencial de acceso a Gitea para el resolver de Tekton. Reemplaza <tu-token-de-gitea> por el token de acceso personal que hayas generado en tu instancia de Gitea.
# Sellar con: kubeseal --cert sealed-secrets-pub.pem --format yaml < gitea-resolver-token.yaml > ../gitea-resolver-token-sealed-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: gitea-resolver-token
  namespace: cnie-tekton-resolvers
type: Opaque
stringData:
  token: <tu-token-de-gitea>
