apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: "{{ repo_name }}-mirror-images-"
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: >
      event == "push" && target_branch == "main" &&
      "harbor-public-images.yaml".pathChanged()
spec:
  taskRunTemplate:
    serviceAccountName: build-push-sa
  pipelineRef:
    resolver: git
    params:
      - name: repo
        value: tekton-pac-pipelines
      - name: pathInRepo
        value: pipelines/mirror-images.yaml
  params:
    - name: gitea-org
      value: "{{ repo_owner }}"
    - name: repo-name
      value: "{{ repo_name }}"
    - name: revision
      value: "{{ revision }}"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          storageClassName: standard
          resources:
            requests:
              storage: 1Gi
