apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - dashboard-ingress.yaml
  - git-resolver-config.yaml
  - cleanup/cleanup-images-cronjob.yaml
  - cleanup/pipelinerun-pruner-cronjob.yaml

configMapGenerator:
  - name: cleanup-pipelinerun-manifest
    namespace: ci
    files:
      - pipelinerun.yaml=cleanup/cleanup-images-pipelinerun.yaml
    options:
      disableNameSuffixHash: true
