apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: app
          image: harbor.harbor.svc.cluster.local:80/ednel/app:41ed156b9a305ebfba8859b43c0eaec50ed850ec
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
