apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - pipeline-serviceaccounts.yaml
  - cleanup/cleanup-images-cronjob.yaml
  - cleanup/pipelinerun-pruner-cronjob.yaml
  - repositories/app.yaml
  - repositories/tekton-cicd-tools.yaml
  - repositories/ansible-playbooks.yaml

configMapGenerator:
  - name: cleanup-pipelinerun-manifest
    namespace: tekton-ci
    files:
      - pipelinerun.yaml=cleanup/cleanup-images-pipelinerun.yaml
    options:
      disableNameSuffixHash: true
