apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cleanup-images-
  namespace: cnie-pipelines-as-code
spec:
  taskRunTemplate:
    serviceAccountName: cleanup-harbor-images-sa
  pipelineRef:
    resolver: git
    params:
      - name: repo
        value: tekton-pac-pipelines
      - name: pathInRepo
        value: pipelines/cleanup-harbor-images.yaml
