apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: "{{ repo_name }}-build-scan-push-"
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, master]"
    pipelinesascode.tekton.dev/max-keep-runs: "30"
spec:
  taskRunTemplate:
    serviceAccountName: build-push-sa
  pipelineRef:
    resolver: git
    params:
      - name: repo
        value: tekton-pac-pipelines
      - name: pathInRepo
        value: pipelines/build-scan-push.yaml
  params:
    - name: repo-owner
      value: "{{ repo_owner }}"
    - name: repo-name
      value: "{{ repo_name }}"
    - name: revision
      value: "{{ revision }}"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          storageClassName: standard #TBR
          resources:
            requests:
              storage: 1Gi #TBR
