apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-scan-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main, master]"
    pipelinesascode.tekton.dev/max-keep-runs: "30"
spec:
  pipelineRef:
    resolver: git
    params:
      - name: repo
        value: infra
      - name: pathInRepo
        value: tekton/pipelines/build-scan-push.yaml
      - name: org
        value: "{{ repo_owner }}"
  params:
    - name: repo-owner
      value: "{{ repo_owner }}"
    - name: repo-name
      value: "{{ repo_name }}"
    - name: revision
      value: "{{ revision }}"
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          storageClassName: standard
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: harbor-credentials
    - name: basic-auth
      secret:
        secretName: gitea-credentials
