apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitea-listener
  namespace: ci
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: build-scan-push
      interceptors:
        - ref:
            kind: ClusterInterceptor
            name: cel
          params:
            - name: filter
              value: >-
                header.canonical('Authorization').compareSecret('secret', 'gitea-webhook-secret') &&
                (body.ref == 'refs/heads/main' || body.ref == 'refs/heads/master')
      bindings:
        - kind: TriggerBinding
          ref: gitea-push-binding
      template:
        ref: build-scan-push-template
