apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: el-gitea-listener-allow-gitea
  namespace: ci
spec:
  podSelector:
    matchLabels:
      eventlistener: gitea-listener
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: gitea
      ports:
        - protocol: TCP
          port: 8080
