apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-scan-push-template
  namespace: ci
spec:
  params:
    - name: revision
    - name: repo-name
    - name: repo-owner
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: build-scan-push-
        namespace: ci
      spec:
        timeouts:
          pipeline: "1h"
          tasks: "45m"
          finally: "10m"
        pipelineRef:
          name: build-scan-push
        serviceAccountName: tekton-pipeline-sa
        params:
          - name: repo-url
            value: http://gitea-http.gitea.svc.cluster.local:3000/$(tt.params.repo-owner)/$(tt.params.repo-name).git #TBD
          - name: revision
            value: $(tt.params.revision)
          - name: image-name
            value: harbor.harbor.svc.cluster.local:80/$(tt.params.repo-owner)/$(tt.params.repo-name) #TBD
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes: [ReadWriteOnce]
                storageClassName: standard #TBD
                resources:
                  requests:
                    storage: 1Gi #TBD
          - name: dockerconfig
            secret:
              secretName: harbor-credentials
          - name: basic-auth
            secret:
              secretName: gitea-credentials
