apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitea-push-binding
  namespace: ci
spec:
  params:
    - name: revision
      value: $(body.after)  # commit SHA
    - name: repo-name
      value: $(body.repository.name)
    - name: repo-owner
      value: $(body.repository.owner.login)
    - name: ref
      value: $(body.ref)
